### ISSUE TITLE
Investigate automatic gosec scan

### ISSUE THREAD

**Issue by yuri-norwood** [yuri-norwood/bfk#141]
https://github.com/securego/gosec#github-action

```yml
name: Run Gosec
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
```
