### ISSUE TITLE
Keep go report card uptodate

### ISSUE THREAD

**Issue by yuri-norwood** [yuri-norwood/bfk#34]
Update workflow to update report card calculation based on [going-gophers/go.yml](https://github.com/yuri-norwood/going-gophers/blob/7d65e14a83ad7a1290aeeca3de453fa6e41ceda7/.github/workflows/go.yml#L75-L78)

```yml
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: creekorful/goreportcard-action@v1.0
```
