### ISSUE TITLE
Automatically assign pull request author

### ISSUE THREAD

**Issue by yuri-norwood** [yuri-norwood/bfk#8]
See [pull_request_automation.yml](https://github.com/yuri-norwood/dotfiles/blob/427fa555cfd252d1ddebc5e7440d5fa672923e3d/.github/workflows/pull_request_automation.yml#L39-L44) in my dotfiles:

```yml
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: samspills/assign-pr-to-author@v1.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
```
